nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%', 'http://localhost:3000'] # FIXME: remove localhost:3000
        allow_headers:
            [
                'X-API-KEY',
                'Origin',
                'X-Requested-With',
                'Content-Type',
                'Accept',
                'Access-Control-Request-Method',
                'Authorization',
            ]
        allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE']
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: true
        forced_allow_origin_value: ~
